/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratwo;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Денис
 */
public class ShortFrame extends BasicFrame {

    private short inputDecValue;
    
    /**
     * Creates new form ShortFrame
     */
    public ShortFrame(JFrame parent) {
        super(parent);
        this.setTitle("Short");
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        inputDec = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        shiftLeft = new javax.swing.JButton();
        shiftRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        byteTable = new javax.swing.JTable();
        resultField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        reverseButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        inputDec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputDecFocusLost(evt);
            }
        });

        jLabel1.setText("Число в десятичной СС");

        shiftLeft.setText("<<");
        shiftLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftLeftActionPerformed(evt);
            }
        });

        shiftRight.setText(">>");
        shiftRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftRightActionPerformed(evt);
            }
        });

        byteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Значение", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}
            },
            new String [] {
                "Вес бита", "32768", "16384", "8192", "4096", "2048", "1024", "512", "256", "128", "64", "32", "16", "8", "4", "2", "1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        byteTable.setShowGrid(true);
        byteTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        byteTable.getColumnModel().getColumn(0).setMaxWidth(60);
        byteTable.getColumnModel().getColumn(0).setMinWidth(60);
        jScrollPane1.setViewportView(byteTable);

        startButton.setText("Перевод");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        reverseButton.setText("Обратный перевод");
        reverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputDec))
                                .addGap(18, 18, 18)
                                .addComponent(shiftLeft)
                                .addGap(18, 18, 18)
                                .addComponent(shiftRight)
                                .addGap(18, 18, 18)
                                .addComponent(startButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(reverseButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shiftLeft)
                            .addComponent(shiftRight)
                            .addComponent(startButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reverseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        int n = 1;  
        for (int i = 0; i < 16; i++, n = (int) Math.pow(2, i))
        {
            int tmp = (inputDecValue & n) > 0 ? 1 : 0;
            this.byteTable.setValueAt(tmp, 0, 16-i);
        }
        this.resultField.setText(String.valueOf(this.inputDecValue));
    }//GEN-LAST:event_startButtonActionPerformed

    private void inputDecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDecFocusLost
        String input = this.inputDec.getText().toString();
        try
        {
            inputDecValue = Short.parseShort(input);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Введите число типа short");
        }
    }//GEN-LAST:event_inputDecFocusLost

    private void shiftRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftRightActionPerformed
        short temp = Short.parseShort(this.resultField.getText().toString());
        temp = (short) (temp >> 1);
        int n = 1;  
        for (int i = 0; i < 16; i++, n = (int) Math.pow(2, i))
        {
            int tmp = (temp & n) > 0 ? 1 : 0;
            this.byteTable.setValueAt(tmp, 0, 16-i);
        }
        this.resultField.setText(String.valueOf(temp));
    }//GEN-LAST:event_shiftRightActionPerformed

    private void shiftLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftLeftActionPerformed
        short temp = Short.parseShort(this.resultField.getText().toString());
        temp = (short) (temp << 1);
        int n = 1;  
        for (int i = 0; i < 16; i++, n = (int) Math.pow(2, i))
        {
            int tmp = (temp & n) > 0 ? 1 : 0;
            this.byteTable.setValueAt(tmp, 0, 16-i);
        }
        this.resultField.setText(String.valueOf(temp));   // TODO add your handling code here:
    }//GEN-LAST:event_shiftLeftActionPerformed

    private void reverseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseButtonActionPerformed
        String binary = "";
        int result = 0;
        Integer t;
        for (int i = 1; i < 17; i++)
        {
            try{
            String tmp = this.byteTable.getValueAt(0, i).toString();
            if (tmp != "")
                t = Integer.parseInt(tmp);
            else
                t = 0;
            if (t == 0 || t == 1) {} else
            {
                throw new Exception("value is " + t + " " + i);
            }
            binary += tmp;
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Неправильные данные в таблице " + e + " " + i);
                return;
            }
        }
        if (Integer.parseInt(this.byteTable.getValueAt(0, 1).toString()) == 0)
            result = Integer.parseInt(binary, 2);
        if (Integer.parseInt(this.byteTable.getValueAt(0, 1).toString()) == 1)
            result = Integer.parseInt(binary, 2) - 65536;
        this.resultField.setText(String.valueOf(result));
    }//GEN-LAST:event_reverseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable byteTable;
    private javax.swing.JTextField inputDec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField resultField;
    private javax.swing.JButton reverseButton;
    private javax.swing.JButton shiftLeft;
    private javax.swing.JButton shiftRight;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
